# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.4-r1

EAPI=8

inherit git-r3 cargo

DESCRIPTION="automate starting binary exploit challenges"
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/WingsZeng/pwninit"
EGIT_REPO_URI="https://github.com/WingsZeng/pwninit.git"
EGIT_BRANCH="dev"

# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="0BSD Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD Boost-1.0 MIT MPL-2.0 Unicode-DFS-2016 Unlicense ZLIB"
SLOT="0"
KEYWORDS=""

DEPEND="
	dev-util/patchelf
"
RDEPEND="${DEPEND}"
BDEPEND=""

# rust does not use *FLAGS from make.conf, silence portage warning
# update with proper path to binaries this crate installs, omit leading /
QA_FLAGS_IGNORED="usr/bin/${PN}"

src_unpack() {
	git-r3_src_unpack
    cargo_live_src_unpack
}

src_compile() {
	# project set strip=true in [profile.release]
	# portage complains: QA Notice: Pre-stripped files found
	# let portage do the strip
	export CARGO_PROFILE_RELEASE_STRIP=false
	export CARGO_PROFILE_RELEASE_LTO=true
	cargo_src_compile
}
