# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.4-r1

EAPI=8

CRATES="
	aho-corasick@1.0.3
	anstream@0.3.2
	anstyle@1.0.1
	anstyle-parse@0.2.1
	anstyle-query@1.0.0
	anstyle-wincon@1.0.2
	autocfg@1.1.0
	bitflags@2.4.0
	cc@1.0.82
	cfg-if@1.0.0
	clap@4.3.21
	clap_builder@4.3.21
	clap_derive@4.3.12
	clap_lex@0.5.0
	colorchoice@1.0.0
	colored@2.0.4
	crossbeam-channel@0.5.8
	crossbeam-deque@0.8.3
	crossbeam-epoch@0.9.15
	crossbeam-utils@0.8.16
	either@1.9.0
	errno@0.3.2
	errno-dragonfly@0.1.2
	goblin@0.7.1
	heck@0.4.1
	hermit-abi@0.3.2
	iced-x86@1.20.0
	is-terminal@0.4.9
	lazy_static@1.4.0
	libc@0.2.147
	linux-raw-sys@0.4.5
	log@0.4.20
	memchr@2.5.0
	memoffset@0.9.0
	num_cpus@1.16.0
	once_cell@1.18.0
	plain@0.2.3
	proc-macro2@1.0.66
	quote@1.0.32
	rayon@1.7.0
	rayon-core@1.11.0
	regex@1.9.3
	regex-automata@0.3.6
	regex-syntax@0.7.4
	rustc-hash@1.1.0
	rustix@0.38.8
	scopeguard@1.2.0
	scroll@0.11.0
	scroll_derive@0.11.1
	strsim@0.10.0
	syn@2.0.28
	thiserror@1.0.44
	thiserror-impl@1.0.44
	unicode-ident@1.0.11
	utf8parse@0.2.1
	windows-sys@0.48.0
	windows-targets@0.48.1
	windows_aarch64_gnullvm@0.48.0
	windows_aarch64_msvc@0.48.0
	windows_i686_gnu@0.48.0
	windows_i686_msvc@0.48.0
	windows_x86_64_gnu@0.48.0
	windows_x86_64_gnullvm@0.48.0
	windows_x86_64_msvc@0.48.0
	${PN}@${PV}
"

inherit cargo

DESCRIPTION="A blazing fast multithreaded ROP Gadget finder. ropper / ropgadget alternative"
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/Ben-Lichtman/ropr"
SRC_URI="${CARGO_CRATE_URIS}"

# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="Apache-2.0 Apache-2.0-with-LLVM-exceptions MIT MPL-2.0 Unicode-DFS-2016 Unlicense"
SLOT="0"
KEYWORDS="~amd64"

DEPEND=""
RDEPEND="${DEPEND}"
BDEPEND=""

# rust does not use *FLAGS from make.conf, silence portage warning
# update with proper path to binaries this crate installs, omit leading /
QA_FLAGS_IGNORED="usr/bin/${PN}"

src_compile() {
	# project set strip=true in [profile.release]
	# portage complains: QA Notice: Pre-stripped files found
	# let portage do the strip
	export CARGO_PROFILE_RELEASE_STRIP=false
	cargo_src_compile
}

