# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.1

EAPI=8

CRATES=""

inherit cargo shell-completion git-r3

DESCRIPTION="An AI agent"
HOMEPAGE="https://github.com/block/goose"
EGIT_REPO_URI="https://github.com/block/goose"

# TODO
RDEPEND=""

LICENSE="Apache-2.0"
# Dependent crate licenses
LICENSE+="
        Apache-2.0 BSD-2 BSD Boost-1.0 CC0-1.0 CDLA-Permissive-2.0 ISC
        LGPL-3+ MIT MIT-0 MPL-2.0 openssl Unicode-3.0 ZLIB
"
SLOT="0"
KEYWORDS=""
IUSE="+extra"

src_unpack() {
    git-r3_src_unpack
    cargo_live_src_unpack
}

src_prepare() {
	default

	if use extra; then
		eapply "${FILESDIR}"/0001-feat-agent-allow-nested-subagents.patch
		# eapply "${FILESDIR}"/0002-feat-session-add-global-recipes-to-common-sessions.patch
		eapply "${FILESDIR}"/0003-feat-subagent-use-extensions-from-recipe.patch
	fi
}

src_compile() {
	cargo_src_compile -p goose-cli
}

src_install() {
	cargo_src_install --path crates/goose-cli

	local goose
	goose="${ED}/usr/bin/goose"

	"$goose" completion zsh | sed 's/#compdef goose-cli/#compdef goose/' >_goose || die
	dozshcomp _goose
}
